name: Upload Python Package

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    -name: Create Virtual Environment
      run: |
      python -m venv env
      source env/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build package
      run: poetry build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        username: __token__
        password: ${{ secrets.TOKEN_API_PYPI }}
    -name: Build Documentation
      run: sphinx-build -b html source/ _build
